### ISSUE TITLE
Darkmode / lightmode buttons in navbar

### ISSUE THREAD

**Issue by AL-thecow** [CBStudentCommunity/Homepage#10]
When we find our new color palette, we'll shift the existing one into darkmode. And have lightmode as default. Should be easy enough to program a function that changes the colors in our css.

**Comment by phynxinferno** [comment]
good idea. we could separate css variables into their own stylesheet and switch between that and a dark mode one

**Comment by AL-thecow** [comment]
as long as everybody is on board

**Comment by gecotron** [comment]
For a lightmode, check the values from [selenized](https://github.com/jan-warchol/selenized/blob/master/the-values.md). I based the website off of the selenized black scheme, so we could also use selenized white for the light mode colourscheme

**Comment by AL-thecow** [comment]
the color scheme for light mode needs to incorporate green, blue and white. If we can make selenized light work with that we are chillin'.

**Comment by phynxinferno** [comment]
Work on this issue has been _sus_pended until the ui remodel is complete due to colour scheme issues.
