### ISSUE TITLE
100% of space on navbar buttons not linked to respective page.

### ISSUE THREAD

**Issue by AL-thecow** [CBStudentCommunity/Homepage#13]
The navbar buttons don't redirect you unless you click on the anchor tag area > The anchor tag area does not fit the div area

**Comment by Nasirahamad88** [comment]
This site is not responsive

**Comment by Jhajeen01** [comment]
I would like to work on this. Can you assign it to me?

**Comment by AL-thecow** [comment]
@Nasirahamad88 can you be a bit more specific?
